name       : haskell-safe-exceptions
version    : 0.1.4.0
release    : 1
source     :
    - http://hackage.haskell.org/package/safe-exceptions-0.1.4.0/safe-exceptions-0.1.4.0.tar.gz : c52078c8457f8233a3796f84a3ae3f336f4668a013ba935e74c7218eeb9a41a6
license    : MIT
component  : programming.haskell
summary    : Safe, consistent, and easy exception handling
description: |
    Safe, consistent, and easy exception handling
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
