name       : haskell-safe-exceptions
version    : 0.1.7.0
release    : 2
source     :
    - https://hackage.haskell.org/package/safe-exceptions-0.1.7.0/safe-exceptions-0.1.7.0.tar.gz : 18cddc587b52b6faa0287fb6ad6c964d1562571ea2c8ff57a194dd54b5fba069
license    : MIT
component  : programming.haskell
summary    : Safe, consistent, and easy exception handling
description: |
    Safe, consistent, and easy exception handling
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
setup      : |
    sed -i "s|0.9|0.11|g" safe-exceptions.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
